### ISSUE TITLE
Fix confusing `EOFError` message on exit

### ISSUE THREAD

**Issue by HippocampusGirl** [HALFpipe/HALFpipe#130]
Remove unnecessary error message to not confuse users

```
Exception ignored in: <function ProcessPoolExecutor._start_queue_management_thread.<locals>.weakref_cb at 0x2ad24deba400>
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/concurrent/futures/process.py", line 567, in weakref_cb
    thread_wakeup.wakeup()
  File "/usr/local/miniconda/lib/python3.7/concurrent/futures/process.py", line 89, in wakeup
    self._writer.send_bytes(b"")
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/connection.py", line 183, in send_bytes
    self._check_closed()
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/connection.py", line 136, in _check_closed
    raise OSError("handle is closed")
OSError: handle is closed
Exception in thread QueueManagerThread:
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/miniconda/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/miniconda/lib/python3.7/concurrent/futures/process.py", line 368, in _queue_management_worker
    thread_wakeup.clear()
  File "/usr/local/miniconda/lib/python3.7/concurrent/futures/process.py", line 93, in clear
    self._reader.recv_bytes()
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
```

**Comment by rfcasseb** [comment]
Dear Lea,

I think I've got a similar error when trying to run the pipeline (below).
Is there anything I should do?

Thank you!

-----------------------------------------------------------------------------------------------------------------------------
singularity run --no-home --cleanenv --bind /:/ext halfpipe_1.1.1.sif

[2021-06-15 11:45:37,0934] [halfpipe        ] [IMPORTANT] Option "--verbose" was not specified. Will not print detailed logs to the terminal. 
└─Detailed logs information will only be available in the "log.txt" file in the working directory. 
[2021-06-15 11:46:19,0892] [nipype.workflow ] [IMPORTANT] 
│     Running fMRIPREP version 20.2.1+halfpipe.3:
│       * BIDS dataset path: /ext/data/rfcasseb/ENIGMA/output/rawdata.
│       * Participant list: ['RadBMdC', 'RadLRP'].
│       * Run identifier: 20210615-114536_89639249-b5f8-44a6-9749-efad351ee613.
└─      * Output spaces: MNI152NLin2009cAsym:res-2.
[2021-06-15 11:46:22,0297] [nipype.workflow ] [IMPORTANT] Slice-timing correction will be included.
[2021-06-15 11:46:22,0636] [nipype.workflow ] [IMPORTANT] Slice-timing correction will be included.
Exception ignored in: <function ProcessPoolExecutor._start_queue_management_thread.<locals>.weakref_cb at 0x7f04fda49bf8>
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/concurrent/futures/process.py", line 567, in weakref_cb
    thread_wakeup.wakeup()
  File "/usr/local/miniconda/lib/python3.7/concurrent/futures/process.py", line 89, in wakeup
    self._writer.send_bytes(b"")
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/connection.py", line 183, in send_bytes
    self._check_closed()
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/connection.py", line 136, in _check_closed
Exception in thread QueueManagerThread:
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/miniconda/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/miniconda/lib/python3.7/concurrent/futures/process.py", line 368, in _queue_management_worker
    thread_wakeup.clear()
  File "/usr/local/miniconda/lib/python3.7/concurrent/futures/process.py", line 92, in clear
    while self._reader.poll():
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/connection.py", line 255, in poll
    self._check_closed()
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/connection.py", line 136, in _check_closed
    raise OSError("handle is closed")
OSError: handle is closed

    raise OSError("handle is closed")
OSError: handle is closed
[2021-06-15 12:49:12,0186] [halfpipe        ] [WARNING  ] Ignoring exception in chunk 2
│     File "/usr/local/miniconda/lib/python3.7/site-packages/halfpipe/cli/run.py", line 250, in run
│         21   def run(opts, should_run):
│      (...)
│         246                  assert isinstance(chunk, nx.DiGraph)
│         247  
│         248                  runner = runnercls(plugin_args=plugin_args)
│         249                  firstnode = first(chunk.nodes())
│     --> 250                  assert isinstance(firstnode, pe.Node)
│         251                  if firstnode is not None:
│         ..................................................
│          opts = Namespace(debug=False, fs_license_file=None, fs_root=PosixPa
│                  th('/ext'), graphs_file=None, keep='some', max_chunk_size=64
│                  , n_chunks=None, nipype_memory_gb=None, nipype_n_procs=96, n
│                  ipype_omp_nthreads=None, nipype_resource_monitor=False, nipy
│                  pe_run_plugin='MultiProc', only_chunk_index=None, only_model
│                  _chunk=False, only_run=False, only_spec_ui=False, only_workf
│                  low=False, profile=False, skip_run=False, skip_spec_ui=False
│                  , skip_workflow=False, subject_chunks=False, subject_exclude
│                  =[], subject_include...
│          should_run = {'spec-ui': True,
│                        'workflow': True,
│                        'run': True}
│          chunk = <networkx.classes.digraph.DiGraph object at 0x7f04fd7f3630>
│          nx.DiGraph = <class 'networkx.classes.digraph.DiGraph'>
│          runner = <halfpipe.plugins.multiproc.MultiProcPlugin object at 0x7f04
│                    f9169a90>
│          runnercls = <class 'halfpipe.plugins.multiproc.MultiProcPlugin'>
│          plugin_args = {'workdir': PosixPath('/ext/data/rfcasseb/ENIGMA/output'),
│                         'watchdog': False,
│                         'stop_on_first_crash': False,
│                         'raise_insufficient': False,
│                         'keep': 'some',
│                         'n_procs': 96,
│                         'memory_gb': 121.3341179904}
│          firstnode = None
│          chunk.nodes = NodeView(())
│          pe.Node = <class 'nipype.pipeline.engine.nodes.Node'>
│         ..................................................
└─    AssertionError

**Comment by HippocampusGirl** [comment]
Dear @rfcasseb,
Did `HALFpipe` generate all the outputs you need? 
As far as I can tell, this error is related to how `HALFpipe` exits once processing is done. Unless you encounter issues with processing, I will not be prioritizing the issue for now :-)

**Comment by rfcasseb** [comment]
Yes, it seems that I have everything here. Thank you so much!

I am sorry to bother, but I have a few questions regarding the preprocessed bold file:
1) Does halfpipe save the preprocessed functional image by default?
2) I guessed not, because of the setting up questions. So I chose to save it, but halfpipe asks again about the preprocessing parameters. Does it create a different file?
3)  Would the preprocessing file be this one: working_dir/derivatives/halfpipe/Subj001/func/sub-RadBMdC_task-enigmaRest_setting-preproc_bold.nii.gz?

Thanks again!

**Comment by HippocampusGirl** [comment]
Dear @rfcasseb,
1) No, not by default. We do this to save disk space.
2) If you choose the same options, then it will be the same file.
3) Yes, exactly!

**Comment by HippocampusGirl** [comment]
Also the following error

```
Exception in thread QueueManagerThread:
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/miniconda/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/miniconda/lib/python3.7/concurrent/futures/process.py", line 368, in _queue_management_worker
    thread_wakeup.clear()
  File "/usr/local/miniconda/lib/python3.7/concurrent/futures/process.py", line 93, in clear
    self._reader.recv_bytes()
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
OSError: [Errno 9] Bad file descriptor
```
