### ISSUE TITLE
User interface error when too many distinct sessions are present

### ISSUE THREAD

**Issue by jwe080** [HALFpipe/HALFpipe#400]
**What happened?**
Halfpipe hangs and exits in error after specifying first level feature (seed_corr).  I'm running halfpipe in a singularity container on an interactive node with BIDS format data. (Maybe it can't find the seed file? but I don't know where that is either, I assumed it was in the container)

**Is there an error message?**
Exception in thread Thread-1 (main):
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/usr/local/miniconda/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/miniconda/lib/python3.10/site-packages/halfpipe/ui/components/app.py", line 56, in main
    raise _error
  File "/usr/local/miniconda/lib/python3.10/site-packages/halfpipe/ui/components/app.py", line 48, in main
    self.loop()
  File "/usr/local/miniconda/lib/python3.10/site-packages/halfpipe/ui/components/app.py", line 96, in loop
    func()
  File "/usr/local/miniconda/lib/python3.10/site-packages/halfpipe/ui/components/view.py", line 58, in draw
    size = self.drawAt(y)
  File "/usr/local/miniconda/lib/python3.10/site-packages/halfpipe/ui/components/input/choice.py", line 243, in drawAt
    return self._drawAt_vertical(y)
  File "/usr/local/miniconda/lib/python3.10/site-packages/halfpipe/ui/components/input/choice.py", line 224, in _drawAt_vertical
    nchr = self._draw_option(i, y + size)
  File "/usr/local/miniconda/lib/python3.10/site-packages/halfpipe/ui/components/input/choice.py", line 546, in _draw_option
    self.layout.window.addstr(y, x, box, color)
_curses.error: addwstr() returned ERR
ls
C^Cexception calling callback for <Future at 0x2aaab9db0910 state=finished returned TeardownMessage>
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.10/concurrent/futures/_base.py", line 329, in _invoke_callbacks
    callback(self)
  File "/usr/local/miniconda/lib/python3.10/asyncio/futures.py", line 398, in _call_set_state
    dest_loop.call_soon_threadsafe(_set_state, destination, source)
  File "/usr/local/miniconda/lib/python3.10/asyncio/base_events.py", line 790, in call_soon_threadsafe
    self._check_closed()
  File "/usr/local/miniconda/lib/python3.10/asyncio/base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Traceback (most recent call last):
  File "/usr/local/miniconda/bin/halfpipe", line 8, in <module>
    sys.exit(main())
  File "/usr/local/miniconda/lib/python3.10/site-packages/halfpipe/cli/run.py", line 327, in main
    run(opts, should_run)
  File "/usr/local/miniconda/lib/python3.10/site-packages/halfpipe/cli/run.py", line 259, in run
    run_stage_ui(opts)
  File "/usr/local/miniconda/lib/python3.10/site-packages/halfpipe/cli/run.py", line 25, in run_stage_ui
    opts.workdir = init_spec_ui(workdir=opts.workdir, debug=opts.debug)
  File "/usr/local/miniconda/lib/python3.10/site-packages/halfpipe/ui/base.py", line 200, in init_spec_ui
    ctx = FirstStep(app)(ctx)
  File "/usr/local/miniconda/lib/python3.10/site-packages/halfpipe/ui/step.py", line 33, in __call__
    new_ctx = self.next(deepcopy(ctx))
  File "/usr/local/miniconda/lib/python3.10/site-packages/halfpipe/ui/base.py", line 176, in next
    return WorkingDirectoryStep(self.app)(ctx)
  File "/usr/local/miniconda/lib/python3.10/site-packages/halfpipe/ui/step.py", line 33, in __call__
    new_ctx = self.next(deepcopy(ctx))
  File "/usr/local/miniconda/lib/python3.10/site-packages/halfpipe/ui/base.py", line 150, in next
    return UseExistingSpecStep(self.app)(ctx)
  File "/usr/local/miniconda/lib/python3.10/site-packages/halfpipe/ui/step.py", line 33, in __call__
    new_ctx = self.next(deepcopy(ctx))
  File "/usr/local/miniconda/lib/python3.10/site-packages/halfpipe/ui/base.py", line 92, in next
    return BidsStep(self.app)(ctx)
  File "/usr/local/miniconda/lib/python3.10/site-packages/halfpipe/ui/step.py", line 33, in __call__
    new_ctx = self.next(deepcopy(ctx))
  File "/usr/local/miniconda/lib/python3.10/site-packages/halfpipe/ui/step.py", line 117, in next
    return choice_step(self.app, **self.kwargs)(ctx)
  File "/usr/local/miniconda/lib/python3.10/site-packages/halfpipe/ui/step.py", line 33, in __call__
    new_ctx = self.next(deepcopy(ctx))
  File "/usr/local/miniconda/lib/python3.10/site-packages/halfpipe/ui/file/bids.py", line 35, in next
    return AnatSummaryStep(self.app)(ctx)
  File "/usr/local/miniconda/lib/python3.10/site-packages/halfpipe/ui/step.py", line 33, in __call__
    new_ctx = self.next(deepcopy(ctx))
  File "/usr/local/miniconda/lib/python3.10/site-packages/halfpipe/ui/pattern.py", line 61, in next
    return self.next_step_type(self.app)(ctx)
  File "/usr/local/miniconda/lib/python3.10/site-packages/halfpipe/ui/step.py", line 33, in __call__
    new_ctx = self.next(deepcopy(ctx))
  File "/usr/local/miniconda/lib/python3.10/site-packages/halfpipe/ui/pattern.py", line 61, in next
    return self.next_step_type(self.app)(ctx)
  File "/usr/local/miniconda/lib/python3.10/site-packages/halfpipe/ui/step.py", line 33, in __call__
    new_ctx = self.next(deepcopy(ctx))
  File "/usr/local/miniconda/lib/python3.10/site-packages/halfpipe/ui/file/func.py", line 113, in next
    return super().next(ctx)
  File "/usr/local/miniconda/lib/python3.10/site-packages/halfpipe/ui/step.py", line 117, in next
    return choice_step(self.app, **self.kwargs)(ctx)
  File "/usr/local/miniconda/lib/python3.10/site-packages/halfpipe/ui/step.py", line 33, in __call__
    new_ctx = self.next(deepcopy(ctx))
  File "/usr/local/miniconda/lib/python3.10/site-packages/halfpipe/ui/file/func.py", line 71, in next
    return self.next_step_type(self.app)(ctx)
  File "/usr/local/miniconda/lib/python3.10/site-packages/halfpipe/ui/step.py", line 33, in __call__
    new_ctx = self.next(deepcopy(ctx))
  File "/usr/local/miniconda/lib/python3.10/site-packages/halfpipe/ui/pattern.py", line 61, in next
    return self.next_step_type(self.app)(ctx)
  File "/usr/local/miniconda/lib/python3.10/site-packages/halfpipe/ui/step.py", line 33, in __call__
    new_ctx = self.next(deepcopy(ctx))
  File "/usr/local/miniconda/lib/python3.10/site-packages/halfpipe/ui/step.py", line 117, in next
    return choice_step(self.app, **self.kwargs)(ctx)
  File "/usr/local/miniconda/lib/python3.10/site-packages/halfpipe/ui/step.py", line 33, in __call__
    new_ctx = self.next(deepcopy(ctx))
  File "/usr/local/miniconda/lib/python3.10/site-packages/halfpipe/ui/feature/base.py", line 108, in next
    return FeatureNameStep(self.app)(ctx)
  File "/usr/local/miniconda/lib/python3.10/site-packages/halfpipe/ui/step.py", line 33, in __call__
    new_ctx = self.next(deepcopy(ctx))
  File "/usr/local/miniconda/lib/python3.10/site-packages/halfpipe/ui/feature/base.py", line 72, in next
    return next_step_type(self.app)(ctx)
  File "/usr/local/miniconda/lib/python3.10/site-packages/halfpipe/ui/step.py", line 33, in __call__
    new_ctx = self.next(deepcopy(ctx))
  File "/usr/local/miniconda/lib/python3.10/site-packages/halfpipe/ui/setting/base.py", line 184, in next
    return SettingFilterStep(self.app)(ctx)
  File "/usr/local/miniconda/lib/python3.10/site-packages/halfpipe/ui/step.py", line 29, in __call__
    if not self.run(ctx):
  File "/usr/local/miniconda/lib/python3.10/site-packages/halfpipe/ui/setting/base.py", line 93, in run
    self.choice = self.input_view()
  File "/usr/local/miniconda/lib/python3.10/site-packages/halfpipe/ui/components/view.py", line 168, in __call__

**What is the exact command that you used to run `Halfpipe`?**
singularity run --containall --bind /data/bids/:/ext halfpipe-halfpipe-latest.sif --use-cluster

**Which settings did you use?**
There isn't a spec.json file anywhere obvious.

**Comment by HippocampusGirl** [comment]
Hi @jwe080,

Could you send me the full log file, either here or via e-mail at <lea@fmri.science>?

**Comment by jwe080** [comment]
Hi @HippocampusGirl,

Log and error files are attached here, they seemed to contain mostly warnings so let me know if these aren't the right ones.

[log.txt](https://github.com/HALFpipe/HALFpipe/files/9364118/log.txt)
[err.txt](https://github.com/HALFpipe/HALFpipe/files/9364122/err.txt)

Thanks!

**Comment by HippocampusGirl** [comment]
Hi @jwe080,

I am not sure what could be causing the issue. For how long did the process hang before you cancelled it?

**Comment by jwe080** [comment]
The process dies immediately after answering the question. Are there files
it is looking for at this point which might not be in the singularity path?
I tried putting the ROI files in different places to no effect.

Le lun. 19 sept. 2022, 05 h 34, Lea Waller ***@***.***> a
écrit :

**Comment by HippocampusGirl** [comment]
Hi @jwe080,

There does not seem to be any obvious error in the log files, so I'm really not sure what might be happening. Would you be available for a short video call to diagnose the problem?

**Comment by HippocampusGirl** [comment]
A blinded data set had sessions coded by acquisition date, so that almost each subject had distinct session identifiers. This causes the `SettingFilterStep` to overflow the curses window.
