### ISSUE TITLE
Error during smoothing 

### ISSUE THREAD

**Issue by hc528** [HALFpipe/HALFpipe#402]
**What happened?**
I installed HALFpipe on my laptop (windows subsystem of linux 2, WSL2) and tried with a task-based fmri analysis. Despite a few warnings that didn't seem to cause any halt to the ongoing processing, there was a crash report while running node 'smoothest' and killed all further steps that follow. 

**Is there an error message?**
[err.txt](https://github.com/HALFpipe/HALFpipe/files/9333041/err.txt)
----- details are as follows
[2022-08-13 11:15:24,0902] [nipype.workflow ] [ERROR    ] Node smoothest failed to run on host DESKTOP-T6PHO1G.
[2022-08-13 11:15:24,0941] [nipype.workflow ] [ERROR    ] Saving crash info to /ext/mnt/d/HALFpipe_try/outputs/crash-20220813-111524-root-smoothest-57f70cfb-f43c-4edc-bd64-d140042c4bbd.txt
│ Traceback (most recent call last):
│   File "/usr/local/miniconda/lib/python3.10/site-packages/nipype/pipeline/plugins/multiproc.py", line 292, in _send_procs_to_workers
│     num_subnodes = self.procs[jobid].num_subnodes()
│   File "/usr/local/miniconda/lib/python3.10/site-packages/nipype/pipeline/engine/nodes.py", line 1290, in num_subnodes
│     self._check_iterfield()
│   File "/usr/local/miniconda/lib/python3.10/site-packages/nipype/pipeline/engine/nodes.py", line 1313, in _check_iterfield
│     raise ValueError(
│ ValueError: Input zstat_file was not set but it is listed in iterfields.
│ When creating this crashfile, the results file corresponding
└─to the node could not be found.
---------

**What is the exact command that you used to run `Halfpipe`?**
singularity run --containall --bind /:/ext /usr/local/halfpipe-halfpipe-1.2.2.sif --keep none --verbose

**Which settings did you use?**
[spec.txt](https://github.com/HALFpipe/HALFpipe/files/9333036/spec.txt)

**Comment by hannah-swe** [comment]
I am facing the exact same issue with HALFpipe version 1.3.1. Any progress towards solving that issue? Thanks very much in advance!
